# Generated by Django 2.2.10 on 2022-06-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of Student', max_length=50)),
                ('roll_no', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
        ),
    ]
