# Generated by Django 4.0.3 on 2022-05-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_user_email_user_name_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogInUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=70, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
